plugins {
	id "dev.prozilla.pine.conventions"
	id "dev.prozilla.pine.examples.conventions"
	id "com.gradleup.shadow" version "8.3.9"
}

application {
	mainClass = "dev.prozilla.pine.examples.sokoban.Main"
}

dependencies {
	implementation "io.netty:netty-all:4.2.17.Final"
	implementation project(":extensions:pi-net")
}

tasks.register("start", JavaExec) {
	mainClass = "dev.prozilla.pine.examples.sokoban.Main"
}